{
  "version": "4.28.0",
  "time": 217.252,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "5c6934c7bb742ef4e1855ba878a39e08",
          "bytes": 56406830,
          "fields": 27,
          "rows": 1846072
        }
      },
      "time": 217.252,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "49902",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "20431",
            "1",
            "32",
            "236",
            "11891",
            "109976",
            "369095",
            "75449",
            "604",
            "1831400",
            "2796",
            "2842",
            "2021",
            "2022-05-13",
            "400.0000",
            "12.2600",
            "4904.00",
            "12.2600",
            "4904.00",
            "4904.00"
          ],
          "rowNumber": 1798952,
          "rowPosition": 1798953,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75449\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1798953\" violates the foreign key: for \"id_contrato\": values \"75449\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "60573",
            "1",
            "32",
            "236",
            "9569",
            "224835",
            "369095",
            "75441",
            "889",
            "1831400",
            "2796",
            "2842",
            "2021",
            "2022-05-13",
            "1.0000",
            "28030.0000",
            "28030.00",
            "28000.0000",
            "28000.00",
            "28000.00"
          ],
          "rowNumber": 1798953,
          "rowPosition": 1798954,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75441\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1798954\" violates the foreign key: for \"id_contrato\": values \"75441\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "27295",
            "1",
            "32",
            "100",
            "13804",
            "149343",
            "369095",
            "75437",
            "480",
            "1831400",
            "2796",
            "2842",
            "2021",
            "2022-05-13",
            "1000.0000",
            "130.0300",
            "130030.00",
            "97.4400",
            "97440.00",
            "97440.00"
          ],
          "rowNumber": 1798954,
          "rowPosition": 1798955,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75437\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1798955\" violates the foreign key: for \"id_contrato\": values \"75437\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "18842",
            "1",
            "32",
            "100",
            "10696",
            "53868",
            "369095",
            "75444",
            "426",
            "1831400",
            "2796",
            "2842",
            "2021",
            "2022-05-13",
            "1.0000",
            "388.2300",
            "388.23",
            "334.4000",
            "334.40",
            "334.40"
          ],
          "rowNumber": 1798955,
          "rowPosition": 1798956,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1798956\" violates the foreign key: for \"id_contrato\": values \"75444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "18842",
            "1",
            "32",
            "100",
            "19228",
            "23571",
            "369095",
            "75444",
            "958",
            "1831400",
            "2796",
            "2842",
            "2021",
            "2022-05-13",
            "1.0000",
            "1102.3300",
            "1102.33",
            "372.0000",
            "372.00",
            "372.00"
          ],
          "rowNumber": 1798956,
          "rowPosition": 1798957,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1798957\" violates the foreign key: for \"id_contrato\": values \"75444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "14",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "58253",
            "1",
            "77",
            "271",
            "1817",
            "94069",
            "369079",
            "75436",
            "1511",
            "1831744",
            "2597",
            "1760",
            "2022",
            "2022-05-13",
            "110.0000",
            "150.0000",
            "16500.00",
            "58.9000",
            "6479.00",
            "6479.00"
          ],
          "rowNumber": 1799403,
          "rowPosition": 1799404,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75436\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799404\" violates the foreign key: for \"id_contrato\": values \"75436\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "32",
            "100",
            "8878",
            "47803",
            "369089",
            "75431",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2021",
            "2022-05-13",
            "500.0000",
            "3.5600",
            "1780.00",
            "1.8300",
            "915.00",
            "915.00"
          ],
          "rowNumber": 1799983,
          "rowPosition": 1799984,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75431\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799984\" violates the foreign key: for \"id_contrato\": values \"75431\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "18842",
            "1",
            "32",
            "100",
            "8900",
            "35984",
            "369089",
            "75444",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2021",
            "2022-05-13",
            "100.0000",
            "24.7500",
            "2475.00",
            "3.2000",
            "320.00",
            "320.00"
          ],
          "rowNumber": 1799984,
          "rowPosition": 1799985,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799985\" violates the foreign key: for \"id_contrato\": values \"75444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "32",
            "100",
            "19668",
            "47919",
            "369089",
            "75431",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2021",
            "2022-05-13",
            "1000.0000",
            "3.1600",
            "3160.00",
            "1.4800",
            "1480.00",
            "1480.00"
          ],
          "rowNumber": 1799985,
          "rowPosition": 1799986,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75431\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799986\" violates the foreign key: for \"id_contrato\": values \"75431\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "32",
            "100",
            "8878",
            "47803",
            "369089",
            "75431",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2021",
            "2022-05-13",
            "500.0000",
            "3.5600",
            "1780.00",
            "1.8300",
            "915.00",
            "915.00"
          ],
          "rowNumber": 1800019,
          "rowPosition": 1800020,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75431\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800020\" violates the foreign key: for \"id_contrato\": values \"75431\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "18842",
            "1",
            "32",
            "100",
            "8900",
            "35984",
            "369089",
            "75444",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2021",
            "2022-05-13",
            "500.0000",
            "24.7500",
            "12375.00",
            "3.2000",
            "1600.00",
            "1600.00"
          ],
          "rowNumber": 1800020,
          "rowPosition": 1800021,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800021\" violates the foreign key: for \"id_contrato\": values \"75444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "18842",
            "1",
            "32",
            "100",
            "19668",
            "77124",
            "369089",
            "75444",
            "433",
            "1831400",
            "2796",
            "3331",
            "2021",
            "2022-05-13",
            "5.0000",
            "373.1100",
            "1865.53",
            "139.0000",
            "695.00",
            "695.00"
          ],
          "rowNumber": 1800021,
          "rowPosition": 1800022,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800022\" violates the foreign key: for \"id_contrato\": values \"75444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "100",
            "1365",
            "39946",
            "369089",
            "75438",
            "433",
            "1831400",
            "2796",
            "3331",
            "2021",
            "2022-05-13",
            "101.0000",
            "295.0000",
            "29795.00",
            "290.0000",
            "29290.00",
            "29290.00"
          ],
          "rowNumber": 1800022,
          "rowPosition": 1800023,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75438\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800023\" violates the foreign key: for \"id_contrato\": values \"75438\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "60573",
            "1",
            "32",
            "100",
            "3708",
            "33898",
            "369089",
            "75441",
            "613",
            "1831400",
            "2796",
            "3331",
            "2021",
            "2022-05-13",
            "3.0000",
            "2682.0200",
            "8046.06",
            "933.3200",
            "2799.96",
            "2799.96"
          ],
          "rowNumber": 1800024,
          "rowPosition": 1800025,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75441\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800025\" violates the foreign key: for \"id_contrato\": values \"75441\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "49902",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "18842",
            "1",
            "32",
            "100",
            "19668",
            "77124",
            "369089",
            "75444",
            "433",
            "1831400",
            "2796",
            "3331",
            "2021",
            "2022-05-13",
            "3.0000",
            "373.1100",
            "1119.32",
            "139.0000",
            "417.00",
            "417.00"
          ],
          "rowNumber": 1800029,
          "rowPosition": 1800030,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800030\" violates the foreign key: for \"id_contrato\": values \"75444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43952",
            "13",
            "1831008",
            "5",
            "1",
            "1",
            "66",
            "68068",
            "1",
            "8",
            "687",
            "12333",
            "92275",
            "370608",
            "75435",
            "889",
            "1831347",
            "2747",
            "2925",
            "2022",
            "2022-06-06",
            "0.0000",
            "114845.2700",
            "114845.27",
            "107498.4000",
            "107498.40",
            "107498.40"
          ],
          "rowNumber": 1800984,
          "rowPosition": 1800985,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75435\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800985\" violates the foreign key: for \"id_contrato\": values \"75435\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50360",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "21252",
            "1",
            "42",
            "399",
            "15832",
            "1841",
            "369618",
            "75448",
            "889",
            "1831334",
            "2923",
            "2081",
            "2022",
            "2022-05-20",
            "2000.0000",
            "0.9100",
            "1820.00",
            "0.9100",
            "1820.00",
            "1820.00"
          ],
          "rowNumber": 1802070,
          "rowPosition": 1802071,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75448\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802071\" violates the foreign key: for \"id_contrato\": values \"75448\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50360",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "21252",
            "1",
            "42",
            "399",
            "6227",
            "36729",
            "369618",
            "75448",
            "889",
            "1831334",
            "2923",
            "2081",
            "2022",
            "2022-05-20",
            "600.0000",
            "16.5500",
            "9930.00",
            "10.3400",
            "6204.00",
            "6204.00"
          ],
          "rowNumber": 1802072,
          "rowPosition": 1802073,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75448\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802073\" violates the foreign key: for \"id_contrato\": values \"75448\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44030",
            "2",
            "1831079",
            "76",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "2941",
            "5465",
            "370346",
            "75428",
            "190",
            "1831313",
            "2928",
            "2046",
            "2022",
            "2022-06-01",
            "660000.0000",
            "5.2100",
            "3439722.00",
            "5.2100",
            "3439722.00",
            "3439722.00"
          ],
          "rowNumber": 1805711,
          "rowPosition": 1805712,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75428\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805712\" violates the foreign key: for \"id_contrato\": values \"75428\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44030",
            "2",
            "1831079",
            "76",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "16006",
            "118342",
            "370346",
            "75428",
            "190",
            "1831313",
            "2928",
            "2046",
            "2022",
            "2022-06-01",
            "120000.0000",
            "5.9900",
            "718260.00",
            "5.9900",
            "718260.00",
            "718260.00"
          ],
          "rowNumber": 1805712,
          "rowPosition": 1805713,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75428\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805713\" violates the foreign key: for \"id_contrato\": values \"75428\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50366",
            "2",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "31915",
            "1",
            "39",
            "130",
            "1824",
            "158672",
            "365737",
            "75439",
            "889",
            "1831812",
            "3065",
            "1760",
            "2022",
            "2022-03-22",
            "0.0000",
            "245824.0000",
            "245824.00",
            "245824.0000",
            "245824.00",
            "245824.00"
          ],
          "rowNumber": 1820164,
          "rowPosition": 1820165,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75439\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820165\" violates the foreign key: for \"id_contrato\": values \"75439\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "21",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "11676",
            "1",
            "77",
            "82",
            "7067",
            "95658",
            "367798",
            "75446",
            "889",
            "1831925",
            "3069",
            "3042",
            "2022",
            "2022-04-26",
            "0.0000",
            "16697.7600",
            "16697.76",
            "16697.7600",
            "16697.76",
            "16697.76"
          ],
          "rowNumber": 1825014,
          "rowPosition": 1825015,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75446\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825015\" violates the foreign key: for \"id_contrato\": values \"75446\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50337",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "313581",
            "368350",
            "75429",
            "889",
            "1831295",
            "2611",
            "2270",
            "2022",
            "2022-05-24",
            "210.0000",
            "8485.0000",
            "1781850.00",
            "5155.8000",
            "1082718.00",
            "1082718.00"
          ],
          "rowNumber": 1827387,
          "rowPosition": 1827388,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75429\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827388\" violates the foreign key: for \"id_contrato\": values \"75429\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44025",
            "1",
            "1831105",
            "50",
            "1",
            "8",
            "879",
            "71244",
            "1",
            "77",
            "479",
            "20171",
            "93519",
            "370644",
            "46296",
            "889",
            "1831808",
            "2602",
            "3042",
            "2022",
            "2022-06-06",
            "0.0000",
            "3465.0000",
            "3465.00",
            "3465.0000",
            "3465.00",
            "3465.00"
          ],
          "rowNumber": 1829859,
          "rowPosition": 1829860,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"71244\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1829860\" violates the foreign key: for \"id_contratado\": values \"71244\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43998",
            "14",
            "1831016",
            "16",
            "1",
            "1",
            "501",
            "67504",
            "1",
            "77",
            "700",
            "20243",
            "92759",
            "369921",
            "75445",
            "889",
            "1831747",
            "2954",
            "2082",
            "2022",
            "2022-05-25",
            "0.0000",
            "2492.9300",
            "2492.93",
            "2001.0000",
            "2001.00",
            "2001.00"
          ],
          "rowNumber": 1832941,
          "rowPosition": 1832942,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832942\" violates the foreign key: for \"id_contrato\": values \"75445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50275",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "551",
            "57978",
            "1",
            "51",
            "384",
            "14882",
            "130529",
            "369458",
            "75440",
            "889",
            "1831520",
            "2670",
            "2633",
            "2021",
            "2022-05-18",
            "0.0000",
            "61200.0000",
            "61200.00",
            "24999.9200",
            "24999.92",
            "24999.92"
          ],
          "rowNumber": 1835162,
          "rowPosition": 1835163,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75440\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835163\" violates the foreign key: for \"id_contrato\": values \"75440\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44025",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "30801",
            "1",
            "3",
            "306",
            "12537",
            "145471",
            "370124",
            "75427",
            "889",
            "1831295",
            "2584",
            "2082",
            "2022",
            "2022-05-27",
            "20.0000",
            "15.0000",
            "300.00",
            "82.7000",
            "1654.00",
            "1654.00"
          ],
          "rowNumber": 1835388,
          "rowPosition": 1835389,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75427\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835389\" violates the foreign key: for \"id_contrato\": values \"75427\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44025",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "30801",
            "1",
            "24",
            "155",
            "8289",
            "241282",
            "370124",
            "75427",
            "582",
            "1831203",
            "2584",
            "2082",
            "2022",
            "2022-05-27",
            "4.0000",
            "334.4300",
            "1337.72",
            "334.0000",
            "1336.00",
            "1336.00"
          ],
          "rowNumber": 1835389,
          "rowPosition": 1835390,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75427\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835390\" violates the foreign key: for \"id_contrato\": values \"75427\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44025",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "30801",
            "1",
            "3",
            "7",
            "17166",
            "168106",
            "370124",
            "75427",
            "889",
            "1831295",
            "2584",
            "2082",
            "2022",
            "2022-05-27",
            "2.0000",
            "2836.0000",
            "5672.00",
            "2836.0000",
            "5672.00",
            "5672.00"
          ],
          "rowNumber": 1835390,
          "rowPosition": 1835391,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75427\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835391\" violates the foreign key: for \"id_contrato\": values \"75427\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50338",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "3160",
            "1",
            "31",
            "133",
            "18508",
            "226024",
            "370398",
            "75432",
            "889",
            "1831307",
            "2586",
            "3331",
            "2022",
            "2022-06-02",
            "200000.0000",
            "0.4100",
            "82000.00",
            "0.2700",
            "54000.00",
            "54000.00"
          ],
          "rowNumber": 1835517,
          "rowPosition": 1835518,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75432\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835518\" violates the foreign key: for \"id_contrato\": values \"75432\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "59714",
            "1",
            "10",
            "312",
            "11095",
            "148212",
            "370411",
            "75447",
            "889",
            "1831307",
            "2586",
            "2081",
            "2022",
            "2022-06-02",
            "150.0000",
            "20.0100",
            "3001.50",
            "13.4700",
            "2020.50",
            "2020.50"
          ],
          "rowNumber": 1835529,
          "rowPosition": 1835530,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75447\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835530\" violates the foreign key: for \"id_contrato\": values \"75447\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "59714",
            "1",
            "10",
            "501",
            "1",
            "15764",
            "370411",
            "75447",
            "867",
            "1831307",
            "2586",
            "2081",
            "2022",
            "2022-06-02",
            "3000.0000",
            "26.8700",
            "80610.00",
            "15.8400",
            "47520.00",
            "47520.00"
          ],
          "rowNumber": 1835530,
          "rowPosition": 1835531,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75447\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835531\" violates the foreign key: for \"id_contrato\": values \"75447\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44001",
            "14",
            "1831044",
            "36",
            "1",
            "1",
            "233",
            "31399",
            "1",
            "32",
            "103",
            "1054",
            "30972",
            "370028",
            "75450",
            "889",
            "1831313",
            "2585",
            "2633",
            "2022",
            "2022-05-26",
            "30.0000",
            "120.0000",
            "3600.00",
            "119.9500",
            "3598.50",
            "3598.50"
          ],
          "rowNumber": 1835607,
          "rowPosition": 1835608,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75450\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835608\" violates the foreign key: for \"id_contrato\": values \"75450\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "21613",
            "1",
            "51",
            "584",
            "9713",
            "184619",
            "370241",
            "75433",
            "889",
            "1831508",
            "2670",
            "3043",
            "2022",
            "2022-05-31",
            "0.0000",
            "48944.5000",
            "48944.50",
            "48944.5000",
            "48944.50",
            "48944.50"
          ],
          "rowNumber": 1835710,
          "rowPosition": 1835711,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75433\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835711\" violates the foreign key: for \"id_contrato\": values \"75433\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43955",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "59714",
            "1",
            "10",
            "501",
            "1",
            "146808",
            "370411",
            "75447",
            "371",
            "1831307",
            "2586",
            "2081",
            "2022",
            "2022-06-02",
            "260.0000",
            "20.0200",
            "5205.20",
            "14.7300",
            "3829.80",
            "3829.80"
          ],
          "rowNumber": 1835867,
          "rowPosition": 1835868,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75447\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1835868\" violates the foreign key: for \"id_contrato\": values \"75447\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "1",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "71159",
            "1",
            "77",
            "479",
            "1836",
            "91508",
            "369758",
            "75442",
            "889",
            "1831808",
            "2806",
            "1760",
            "2022",
            "2022-05-23",
            "0.0000",
            "145000.0000",
            "145000.00",
            "145000.0000",
            "145000.00",
            "145000.00"
          ],
          "rowNumber": 1838533,
          "rowPosition": 1838534,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75442\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1838534\" violates the foreign key: for \"id_contrato\": values \"75442\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43959",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "70009",
            "1",
            "75",
            "227",
            "5271",
            "194440",
            "369714",
            "75443",
            "889",
            "1831304",
            "3018",
            "2082",
            "2022",
            "2022-05-23",
            "14.0000",
            "4710.3900",
            "65945.46",
            "2928.2100",
            "40994.94",
            "40994.94"
          ],
          "rowNumber": 1841088,
          "rowPosition": 1841089,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75443\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1841089\" violates the foreign key: for \"id_contrato\": values \"75443\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43974",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "439",
            "14289",
            "1",
            "9",
            "576",
            "9436",
            "186638",
            "368767",
            "75430",
            "889",
            "1831365",
            "2736",
            "3043",
            "2022",
            "2022-05-10",
            "0.0000",
            "4800.0000",
            "4800.00",
            "2100.0000",
            "2100.00",
            "2100.00"
          ],
          "rowNumber": 1845311,
          "rowPosition": 1845312,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75430\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1845312\" violates the foreign key: for \"id_contrato\": values \"75430\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43974",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "439",
            "14289",
            "1",
            "9",
            "576",
            "9436",
            "186633",
            "368767",
            "75430",
            "889",
            "1831365",
            "2736",
            "3043",
            "2022",
            "2022-05-10",
            "0.0000",
            "4800.0000",
            "4800.00",
            "7200.0000",
            "7200.00",
            "7200.00"
          ],
          "rowNumber": 1845312,
          "rowPosition": 1845313,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75430\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1845313\" violates the foreign key: for \"id_contrato\": values \"75430\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43974",
            "17",
            "1831095",
            "96",
            "1",
            "1",
            "66",
            "67653",
            "1",
            "3",
            "237",
            "10538",
            "268654",
            "366656",
            "75434",
            "889",
            "1831295",
            "2611",
            "3955",
            "2022",
            "2022-04-05",
            "30.0000",
            "3197.4000",
            "95922.00",
            "3197.4000",
            "95922.00",
            "95922.00"
          ],
          "rowNumber": 1845366,
          "rowPosition": 1845367,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75434\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1845367\" violates the foreign key: for \"id_contrato\": values \"75434\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 40
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 40,
    "tasks": 1
  },
  "valid": false
}